services:
    tas2580.whatsapp.listener:
        class: tas2580\whatsapp\event\listener
        arguments:
            - @request
            - @user
            - @template
            - @service_container
            - %core.root_path%
        tags:
            - { name: event.listener }
    tas2580.whatsapp.helper:
        class: tas2580\whatsapp\helper
        arguments:
            - @config
            - @user
            - %core.root_path%
            - %core.php_ext%
    notification.method.whatsapp:
        class: tas2580\whatsapp\notification\method\whatsapp
        scope: prototype
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: notification.method }